trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'vsazure.azurecr.io'

steps:
- script: echo 'Iniciando Docker Build y Compose'
  displayName: 'Iniciando Docker Build y Compose'

- task: Docker@2
  displayName: 'Construir Imagen Docker'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Subir Imagen Docker al Registro'
  inputs:
    command: 'push'
    tags: 'latest'
    containerRegistry: $(dockerRegistryServiceConnection)

- task: Docker@2
  displayName: 'Docker Compose Up'
  inputs:
    command: 'composeUp'
    dockerComposeFile: '**/docker-compose.yml'
    removeContainersOnPull: true
    detachedService: true
