image: python:3.9

stages:
  - plot
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install matplotlib numpy pandas

plot:
  stage: plot
  script:
    - python script_grafica.py  # Este script genera grafica_ejemplo.png
  artifacts:
    paths:
      - grafica_ejemplo.png  # Esto asegura que grafica_ejemplo.png este disponible para la siguiente etapa

deploy:
  stage: deploy
  script:
    # Instala pandoc
    - apt-get update && apt-get install -y pandoc
    # Genera el HTML del Markdown
    - pandoc README.md --self-contained -o documentation.html #Para que se incruste la grafica, debemos añadir <![](grafica_ejemplo.png)> en el README.md
  artifacts:
    paths:
      - documentation.html  # The HTML file now includes the embedded image

